# These are supported funding model platforms

Custom: Right now, you can only sponsor me by contacting me personally on social media. 
Unfortunately, for those outside of Russia and China, the only way is to send money to my sisters 
in Ukraine or help my friends and acquaintances from different countries (Ive seen a lot in my life). 
Considering my projects arent that exciting, I doubt theyll support me xddd. 
Ill try to add a proper way to support them later.
